### ISSUE TITLE
cannot find the car dataset

### ISSUE THREAD

**Issue by cctt126** [beerboaa/Color-Classification-CNN#1]
thanks for sharing the code.
I couldn't find the image dataset from the original paper and from the reference [2] inside that paper neither. Would you please provide the image dataset as well, thanks!

**Comment by cctt126** [comment]
Luckily I found the download address:
http://mclab.eic.hust.edu.cn/~pchen/color.rar
hope it can helps others.

**Comment by beerboaa** [comment]
Thank you so much !!
Sorry for this late reply.
I used the dataset collected on my own.
I really appreciate that you posted the link, thanks again !

**Comment by yy9568** [comment]
@cctt126 Hi, the link is broken now, Could you share a duplicate dataset with me? Thank you.

**Comment by thaitrinh** [comment]
Can anyone please share a duplicate dataset with me as well? The link doesn't work anymore. Thank you!
