### ISSUE TITLE
Where can i find the dataset?

### ISSUE THREAD

**Issue by shahidammer** [beerboaa/Color-Classification-CNN#2]

**Comment by beerboaa** [comment]
Hello, 
I trained the model on a private dataset.
The way I trained this was that I created train and test directories including subdirectory for each class.
You might have a look onto Keras ImageDataGenerator (https://keras.io/preprocessing/image/)

**Comment by abramjos** [comment]
http://cloud.eic.hust.edu.cn:8071/~pchen/project.html
Here is the dataset.

**Comment by AqsaHassan** [comment]
I'm unable to load this page... could you please share this dataset? @abramjos
