### ISSUE TITLE
Can't really find dataset.

### ISSUE THREAD

**Issue by ahmedosama9777** [beerboaa/Color-Classification-CNN#9]
Was anybody able to find the dataset?

**Comment by abhirajasp** [comment]
Same here. Not able to find dataset. Found this link but it's not working - 

http://mclab.eic.hust.edu.cn/~pchen/project.html

Found at - 

https://github.com/handong1587/handong1587.github.io/blob/master/_posts/computer_vision/2015-09-24-datasets.md
